USE NexGenCoSysDBDev;
GO

SELECT COLUMN_NAME, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'MemMemberRegistration';


USE info;
GO

SELECT MemberId
FROM members
WHERE ISNUMERIC(MemberId) = 0;
